### ISSUE TITLE
Bones don't work 

### ISSUE THREAD

**Issue by Hilldamn** [kitepro/UnityIKSystem#2]
here is a video of the problem -> https://www.youtube.com/watch?v=SXB5rRf31Og&feature=youtu.be

**Comment by HugoCortell** [comment]
Im having similar problems, I hope the creator updates the demo video to showcase some of the new features.

**Comment by nishadtardalkar** [comment]
Hmm.. Idk why I didnt received notification email for this thread.
https://www.youtube.com/watch?v=4FMOBhg3xaM
Sid S has commented on how to get the bones working.
I was also working on nested IKs and some other updates to this so I havent made any detailed video yet.
